version: "3"
services:
    builder:
        build:
            context: ./image
            dockerfile: Dockerfile
        image: hypriot-kit:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - hypriot-artifacts:/opt/app/artifacts

volumes:
    hypriot-artifacts:
        external: true
